// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fahxygxwggeetaknmszf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhaHh5Z3h3Z2dlZXRha25tc3pmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzODA2OTgsImV4cCI6MjA3Nzk1NjY5OH0.PMKl54EfbWXBAvJMS0iVQX3NYnIykVHtC2e2LaJZ4xI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});