// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gknldnrakdjjtcodtibo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdrbmxkbnJha2RqanRjb2R0aWJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2ODE1MzMsImV4cCI6MjA3MzI1NzUzM30.vmNecls75aD_Pw_n9y4n15G6dxxceLcv9B4dUramE0M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});